### ISSUE TITLE
Minor issues with README

### ISSUE THREAD

**Issue by rparrett** [Lommix/bevy_nine_slice_ui#2]
https://github.com/Lommix/bevy_nine_slice_ui/blob/master/README.md?plain=1#L13C1-L13C25

I think this is still true, but slightly confusing given the example immediately below involves the bundle.

https://github.com/Lommix/bevy_nine_slice_ui/blob/master/README.md?plain=1#L16

This seems to actually be `NineSlicePlugin` rather than `NineSliceUiPlugin`. Though perhaps it's the plugin that should be renamed?

**Comment by Lommix** [comment]
Naming, my worst enemy. It should be  `NinceSliceUiPlugin` and also `NineSliceUiMaterialBundle` instead of `NineSliceMaterialBundle`

**Comment by Lommix** [comment]
fixed in 0.5
