### ISSUE TITLE
Hot reloading only works properly when the image size stays the same.

### ISSUE THREAD

**Issue by rparrett** [Lommix/bevy_nine_slice_ui#3]
Version tested: b74c871eb4380fddfe7cf4f2aca8ae650916ad62

To reproduce, run with `--features=bevy/file_watcher`. Modify your nine slice image by resizing it. The effect is the most disturbing when making the image smaller.

<img width="1280" alt="image" src="https://github.com/Lommix/bevy_nine_slice_ui/assets/200550/857d10ba-74b7-4127-b4ab-3ba4f5809c91">

**Comment by Lommix** [comment]
The texture bounds need to be recalculated in the sync function. This is currently not the case, expect a fix in the within the next day.

**Comment by Lommix** [comment]
Fixed in 0.5
